model = ModelData()
model:setName("shield_generator")
model:setRadius(75)
model:setScale(1.5)
model:setMesh("Shield bubble generator.obj")
model:setTexture("Shield bubble generator.jpg")
model:setSpecular("Shield bubble generator specular.jpg")

--model = ModelData()
--model:setName("space_station_4")
--model:setMesh("space_station_4/space_station_4.model")
--model:setTexture("space_station_4/space_station_4_color.jpg")
--model:setSpecular("space_station_4/space_station_4_specular.jpg")
--model:setIllumination("space_station_4/space_station_4_illumination.jpg")
--model:setRenderOffset(0, 0, 5)
--model:setScale(10)
--model:setRadius(300)
--model:setCollisionBox(400, 400)

model = ModelData()
model:setName("space_station_3")
model:setMesh("space_station_3/space_station_3.model")
model:setTexture("space_station_3/space_station_3_color.jpg")
model:setSpecular("space_station_3/space_station_3_specular.jpg")
model:setIllumination("space_station_3/space_station_3_illumination.jpg")
model:setRenderOffset(10, 0, 5)
model:setScale(10)
model:setRadius(500)
model:setCollisionBox(600, 500)

model = ModelData()
model:setName("space_station_2")
model:setMesh("space_station_2/space_station_2.model")
model:setTexture("space_station_2/space_station_2_color.jpg")
model:setSpecular("space_station_2/space_station_2_specular.jpg")
model:setIllumination("space_station_2/space_station_2_illumination.jpg")
model:setRenderOffset(10, 0, 5)
model:setScale(10)
model:setRadius(650)
model:setCollisionBox(700, 500)
--
--model = ModelData()
--model:setName("space_station_1")
--model:setMesh("space_station_1/space_station_1.model")
--model:setTexture("space_station_1/space_station_1_color.jpg")
--model:setSpecular("space_station_1/space_station_1_specular.jpg")
--model:setIllumination("space_station_1/space_station_1_illumination.jpg")
--model:setRenderOffset(0, 0, 5)
--model:setScale(10)
--model:setRadius(750)
--model:setCollisionBox(1000, 900)

require("config/players.lua")
require("config/enemies.lua")
local radiuses = {}

for _, conf in pairs(PlayerShipTemplates) do
    radiuses[conf.model] = conf.radius
end
for _, conf in pairs(EnemyShipTemplates) do
    radiuses[conf.model] = conf.radius
end

for _, color in ipairs(PlayerShipColors) do
    model = ModelData()
    model:setName("AdlerLongRangeScout" .. color)
    model:setMesh("AdlerLongRangeScout/AdlerLongRangeSoutHull.model")
    model:setTexture("AdlerLongRangeScout/AlbedoAO/AdlerLongRangeScout"..color.."AlbedoAO.png")
    model:setSpecular("AdlerLongRangeScout/AdlerLongRangeScoutPBRSpecular.png")
    model:setIllumination("AdlerLongRangeScout/AdlerLongRangeScoutIllumination.png")
    model:setScale(radiuses["AdlerLongRangeScout"] * 0.7)
    model:setRadius(radiuses["AdlerLongRangeScout"])
    --model:addBeamPosition(1.8, 0, 0.03)
    --model:addBeamPosition(1.8, 0.13, 0.03)
    --model:addBeamPosition(1.8,-0.13, 0.03)
    --model:addTubePosition(1.8, 0, 0.03)
    model:addEngineEmitter(-1.5, 0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, -0.13,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5, 0.42, 0.33,  0.5, 0.5, 1.0, 0.5)
    model:addEngineEmitter(-1.5,-0.42, 0.33,  0.5, 0.5, 1.0, 0.5)

    model = ModelData()
    model:setName("AtlasHeavyFighter" .. color)
    model:setMesh("AtlasHeavyFighter/AtlasHeavyFighterHull.model")
    model:setTexture("AtlasHeavyFighter/AlbedoAO/AtlasHeavyFighter"..color.."AlbedoAO.png")
    model:setSpecular("AtlasHeavyFighter/AtlasHeavyFighterPBRSpecular.png")
    model:setIllumination("AtlasHeavyFighter/AtlasHeavyFighterIllumination.png")
    model:setScale(radiuses["AtlasHeavyFighter"] * 0.6)
    model:setRadius(radiuses["AtlasHeavyFighter"])
    --model:addBeamPosition(2.4, 0.1, -0.25)
    --model:addBeamPosition(2.4,-0.1, -0.25)
    --model:addTubePosition(1, 0.4, 0)
    --model:addTubePosition(1,-0.4, 0)
    --model:addTubePosition(-1, 0, 0) --Mine tube
    model:addEngineEmitter(-1.1, 0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1, 1.05, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-0.7, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1.1,-1.05, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("LindwurmFighter" .. color)
    model:setMesh("LindwurmFighter/LindwurmFighterHull.model")
    model:setTexture("LindwurmFighter/AlbedoAO/LindwurmFighter"..color.."AlbedoAO.png")
    model:setSpecular("LindwurmFighter/LindwurmFighterPBRSpecular.png")
    model:setIllumination("LindwurmFighter/LindwurmFighterIllumination.png")
    model:setScale(radiuses["LindwurmFighter"] * 0.7)
    model:setRadius(radiuses["LindwurmFighter"])
    --model:addTubePosition(1.4, 0, 0.06)
    --model:addTubePosition(0.3, 0.5, 0.06)
    --model:addTubePosition(0.3,-0.5, 0.06)
    model:addEngineEmitter(-1, 0.54, 0.0,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-1,-0.54, 0.0,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("WespeScout" .. color)
    model:setMesh("WespeScout/WespeScoutHull.model")
    model:setTexture("WespeScout/AlbedoAO/WespeScout"..color.."AlbedoAO.png")
    model:setSpecular("WespeScout/WespeScoutPBRSpecular.png")
    model:setIllumination("WespeScout/WespeScoutIllumination.png")
    model:setScale(radiuses["WespeScout"] * 0.7)
    model:setRadius(radiuses["WespeScout"])
    --model:addBeamPosition(1.15, 0.13, -0.03)
    --model:addBeamPosition(1.15,-0.13, -0.03)
    model:addEngineEmitter(-0.2, 0.44, -0.03,  0.5, 0.5, 1.0, 0.4)
    model:addEngineEmitter(-0.2,-0.44, -0.03,  0.5, 0.5, 1.0, 0.4)

    model = ModelData()
    model:setName("HeavyCorvette" .. color)
    model:setMesh("HeavyCorvette/HeavyCorvette.model")
    model:setTexture("HeavyCorvette/AlbedoAO/HeavyCorvette"..color.."AlbedoAO.png")
    model:setSpecular("HeavyCorvette/HeavyCorvettePBRSpecular.png")
    model:setIllumination("HeavyCorvette/HeavyCorvetteIllumination.png")
    model:setScale(radiuses["HeavyCorvette"] * 0.6)
    model:setRadius(radiuses["HeavyCorvette"])
    model:addTubePosition(0.8, 0.8, 0.15)
    model:addTubePosition(0.8, -0.8, 0.15)
    model:addTubePosition(1, 0.4, 0.5)
    model:addTubePosition(1, -0.4, 0.5)
    model:addEngineEmitter(-1.4, 0.4, 0.0,  0.5, 0.5, 1.0, 0.6)
    model:addEngineEmitter(-1.4, 0.0, 0.0,  0.5, 0.5, 1.0, 0.6)
    model:addEngineEmitter(-1.4,-0.4, 0.0,  0.5, 0.5, 1.0, 0.6)

    model = ModelData()
    model:setName("LaserCorvette" .. color)
    model:setMesh("LaserCorvette/LaserCorvette.model")
    model:setTexture("LaserCorvette/AlbedoAO/LaserCorvette"..color.."AlbedoAO.png")
    model:setSpecular("LaserCorvette/LaserCorvettePBRSpecular.png")
    model:setIllumination("LaserCorvette/LaserCorvetteIllumination.png")
    model:setScale(radiuses["LaserCorvette"] * 0.6)
    model:setRadius(radiuses["LaserCorvette"])
    model:addTubePosition(-0.4, 1.2, 0.5)
    model:addTubePosition(-0.4, -1.2, 0.5)
    model:addTubePosition(1, 0, 0.5)
    model:addEngineEmitter(-1.67, 0.1, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-1.67,-0.1, 0.0,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("LightCorvette" .. color)
    model:setMesh("LightCorvette/LightCorvette.model")
    model:setTexture("LightCorvette/AlbedoAO/LightCorvette"..color.."AlbedoAO.png")
    model:setSpecular("LightCorvette/LightCorvettePBRSpecular.png")
    model:setIllumination("LightCorvette/LightCorvetteIllumination.png")
    model:setScale(radiuses["LightCorvette"] * 0.7)
    model:setRadius(radiuses["LightCorvette"])
    model:addTubePosition(0.5, 0.5, 0.15)
    model:addTubePosition(0.5, -0.5, 0.15)
    model:addTubePosition(1, 0, 0.5)
    model:addEngineEmitter(-1.3, 0.22, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3, 0.00, 0.15,  0.5, 0.5, 1.0, 0.3)
    model:addEngineEmitter(-1.3,-0.22, 0.15,  0.5, 0.5, 1.0, 0.3)

    model = ModelData()
    model:setName("MineLayerCorvette" .. color)
    model:setMesh("MineLayerCorvette/MineLayerCorvette.model")
    model:setTexture("MineLayerCorvette/AlbedoAO/MineLayerCorvette"..color.."AlbedoAO.png")
    model:setSpecular("MineLayerCorvette/MineLayerCorvettePBRSpecular.png")
    model:setIllumination("MineLayerCorvette/MineLayerCorvetteIllumination.png")
    model:setScale(radiuses["MineLayerCorvette"] * 0.6)
    model:setRadius(radiuses["MineLayerCorvette"])
    model:addEngineEmitter(-0.65, 0.70, 0.0,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.65,-0.70, 0.0,  0.5, 0.5, 1.0, 0.2)

    model = ModelData()
    model:setName("MultiGunCorvette" .. color)
    model:setMesh("MultiGunCorvette/MultiGunCorvette.model")
    model:setTexture("MultiGunCorvette/AlbedoAO/MultiGunCorvette"..color.."AlbedoAO.png")
    model:setSpecular("MultiGunCorvette/MultiGunCorvettePBRSpecular.png")
    model:setIllumination("MultiGunCorvette/MultiGunCorvetteIllumination.png")
    model:setScale(radiuses["MultiGunCorvette"] * 0.6)
    model:setRadius(radiuses["MultiGunCorvette"])
    model:addEngineEmitter(-0.75, 0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75, 0.0,-0.03,  0.5, 0.5, 1.0, 0.2)
    model:addEngineEmitter(-0.75,-0.2,-0.03,  0.5, 0.5, 1.0, 0.2)
end

model = ModelData()
model:setName("Eagle")
model:setMesh("small_frigate_1/small_frigate_1.model")
model:setTexture("small_frigate_1/small_frigate_1_color.png")
model:setSpecular("small_frigate_1/small_frigate_1_specular.png")
model:setIllumination("small_frigate_1/small_frigate_1_illumination.png")
model:setScale(radiuses["Eagle"] / 130)
model:setRadius(radiuses["Eagle"])
model:addEngineEmitter(-85, 33, 2,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-85, 33, 14,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-85,-33, 2,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-85,-33, 14,  0.2, 0.2, 1.0, 8.0)

--model = ModelData()
--model:setName("small_frigate_2")
--model:setMesh("small_frigate_2/small_frigate_2.model")
--model:setTexture("small_frigate_2/small_frigate_2_color.png")
--model:setSpecular("small_frigate_2/small_frigate_2_specular.png")
--model:setIllumination("small_frigate_2/small_frigate_2_illumination.png")
--model:setScale(1)
--model:setRadius(80)
--
--model:addEngineEmitter(-75, 53,-27,  0.2, 0.2, 1.0, 8.0)
--model:addEngineEmitter(-75,-53,-27,  0.2, 0.2, 1.0, 8.0)

model = ModelData()
model:setName("Stinger")
model:setMesh("small_frigate_3/small_frigate_3.model")
model:setTexture("small_frigate_3/small_frigate_3_color.png")
model:setSpecular("small_frigate_3/small_frigate_3_specular.png")
model:setIllumination("small_frigate_3/small_frigate_3_illumination.png")
model:setScale(radiuses["Stinger"] / 130)
model:setRadius(radiuses["Stinger"])
model:addEngineEmitter(-91, 32,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-95, 32,-17,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-91,-32,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-95,-32,-17,  0.2, 0.2, 1.0, 8.0)

model = ModelData()
model:setName("Owl")
model:setMesh("small_frigate_4/small_frigate_4.model")
model:setTexture("small_frigate_4/small_frigate_4_color.png")
model:setSpecular("small_frigate_4/small_frigate_4_specular.png")
model:setIllumination("small_frigate_4/small_frigate_4_illumination.png")
model:setScale(radiuses["Owl"] / 130)
model:setRadius(radiuses["Owl"])
model:addEngineEmitter(-81, 10,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-81,  0,-4,  0.2, 0.2, 1.0, 8.0)
model:addEngineEmitter(-81,-10,-4,  0.2, 0.2, 1.0, 8.0)
--
--model = ModelData()
--model:setName("small_frigate_5")
--model:setMesh("small_frigate_5/small_frigate_5.model")
--model:setTexture("small_frigate_5/small_frigate_5_color.png")
--model:setSpecular("small_frigate_5/small_frigate_5_specular.png")
--model:setIllumination("small_frigate_5/small_frigate_5_illumination.png")
--model:setScale(1)
--model:setRadius(80)
--
--model:addEngineEmitter(-95, 30, 8,  0.2, 0.2, 1.0, 5.0)
--model:addEngineEmitter(-95, 30, 0,  0.2, 0.2, 1.0, 5.0)
--model:addEngineEmitter(-95, 30,-8,  0.2, 0.2, 1.0, 5.0)
--model:addEngineEmitter(-95,-30, 8,  0.2, 0.2, 1.0, 5.0)
--model:addEngineEmitter(-95,-30, 0,  0.2, 0.2, 1.0, 5.0)
--model:addEngineEmitter(-95,-30,-8,  0.2, 0.2, 1.0, 5.0)

model = ModelData()
model:setName("Drone")
model:setMesh("dark_fighter_6.model")
model:setTexture("dark_fighter_6_color.png")
model:setSpecular("dark_fighter_6_specular.png")
model:setIllumination("dark_fighter_6_illumination.png")
model:setScale(radiuses["Drone"] / 31)
model:setRadius(radiuses["Drone"])
model:addBeamPosition(21, -28.2, -2)
model:addBeamPosition(21,  28.2, -2)
model:addEngineEmitter(-28, -1.5, -5,  1.0, 0.2, 0.2, 3.0)
model:addEngineEmitter(-28,  1.5, -5,  1.0, 0.2, 0.2, 3.0)


model = ModelData():setName("Boomalope")
model:setScale(radiuses["Boomalope"] / 300)
model:setRadius(radiuses["Boomalope"])
model:setCollisionBox(radiuses["Boomalope"] * 2, radiuses["Boomalope"] * 4/3)
model:setMesh("transport_space_ship_1/transport_space_ship_1_cargo_1.model")
model:setTexture("transport_space_ship_1/transport_space_ship_1_color.png")
model:setSpecular("transport_space_ship_1/transport_space_ship_1_specular.png")
model:setIllumination("transport_space_ship_1/transport_space_ship_1_illumination.png")

model = ModelData():setName("Lion")
model:setScale(radiuses["Lion"] / 300)
model:setRadius(radiuses["Lion"])
model:setCollisionBox(radiuses["Lion"] * 2, radiuses["Lion"] * 4/3)
model:setMesh("transport_space_ship_2/transport_space_ship_2_cargo_1.model")
model:setTexture("transport_space_ship_2/transport_space_ship_2_color.png")
model:setSpecular("transport_space_ship_2/transport_space_ship_2_specular.png")
model:setIllumination("transport_space_ship_2/transport_space_ship_2_illumination.png")

model = ModelData():setName("Croco")
model:setScale(radiuses["Croco"] / 300)
model:setRadius(radiuses["Croco"])
model:setCollisionBox(radiuses["Croco"] * 2, radiuses["Croco"] * 4/3)
model:setMesh("transport_space_ship_3/transport_space_ship_3_cargo_1.model")
model:setTexture("transport_space_ship_3/transport_space_ship_3_color.png")
model:setSpecular("transport_space_ship_3/transport_space_ship_3_specular.png")
model:setIllumination("transport_space_ship_3/transport_space_ship_3_illumination.png")

model = ModelData():setName("Perisher")
model:setScale(radiuses["Perisher"] / 300)
model:setRadius(radiuses["Perisher"])
model:setCollisionBox(radiuses["Perisher"] * 2, radiuses["Perisher"] * 4/3)
model:setMesh("transport_space_ship_4/transport_space_ship_4_cargo_1.model")
model:setTexture("transport_space_ship_4/transport_space_ship_4_color.png")
model:setSpecular("transport_space_ship_4/transport_space_ship_4_specular.png")
model:setIllumination("transport_space_ship_4/transport_space_ship_4_illumination.png")

model = ModelData():setName("Porcupine")
model:setScale(radiuses["Porcupine"] / 300)
model:setRadius(radiuses["Porcupine"])
model:setCollisionBox(radiuses["Porcupine"] * 2, radiuses["Porcupine"] * 4/3)
model:setMesh("transport_space_ship_5/transport_space_ship_5_cargo_1.model")
model:setTexture("transport_space_ship_5/transport_space_ship_5_color.png")
model:setSpecular("transport_space_ship_5/transport_space_ship_5_specular.png")
model:setIllumination("transport_space_ship_5/transport_space_ship_5_illumination.png")


model = ModelData()
model:setName("Shark")
model:setMesh("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded.model")
model:setTexture("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_1_upgraded/battleship_destroyer_1_upgraded_illumination.jpg")
model:setScale(radiuses["Shark"] / 50)
model:setRadius(radiuses["Shark"])
model:addBeamPosition(34, -17, -7)
model:addBeamPosition(34,  17, -7)
model:addBeamPosition(-5, -33, -1)
model:addBeamPosition(-5,  33, -1)
model:addTubePosition(5, -7, -11)
model:addTubePosition(5,  7, -11)
model:addEngineEmitter(-30, 0, -3,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-33, 12, -1,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-33,-12, -1,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-33, 22, -1,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-33,-22, -1,  1.0, 0.2, 0.1, 14.0)

model = ModelData()
model:setName("Kraken")
model:setMesh("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded.model")
model:setTexture("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_2_upgraded/battleship_destroyer_2_upgraded_illumination.jpg")
model:setScale(radiuses["Kraken"] / 50)
model:setRadius(radiuses["Kraken"])
model:addBeamPosition(37, -14.5, -3.5)
model:addBeamPosition(37,  14.5, -3.5)
model:addBeamPosition(10, -12, -15)
model:addBeamPosition(10,  12, -15)
model:addBeamPosition(-9, -28, -3)
model:addBeamPosition(-9,  28, -3)
model:addEngineEmitter(-33, 0, -3,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-36, 14, -4,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-36,-14, -4,  1.0, 0.2, 0.1, 17.0)

model = ModelData()
model:setName("Tuna")
model:setMesh("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded.model")
model:setTexture("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded_color.jpg")
model:setSpecular("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded_specular.jpg")
model:setIllumination("battleship_destroyer_3_upgraded/battleship_destroyer_3_upgraded_illumination.jpg")
model:setScale(radiuses["Tuna"] / 50)
model:setRadius(radiuses["Tuna"])
model:addBeamPosition(22,  22, -4.5)
model:addBeamPosition(22, -22, -4.5)
model:addBeamPosition(12,  22, -4.5)
model:addBeamPosition(12, -22, -4.5)

model:addEngineEmitter(-34, 0, 0,  1.0, 0.2, 0.1, 14.0)
model:addEngineEmitter(-36, 13, 0,  1.0, 0.2, 0.1, 17.0)
model:addEngineEmitter(-36,-13, 0,  1.0, 0.2, 0.1, 17.0)
